# Generated by Django 5.0.3 on 2024-04-10 10:13

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0013_merge_20240331_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.discount_img_directory_path,
            ),
        ),
    ]
