# Generated by Django 4.1.5 on 2024-03-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
    ]
