# Generated by Django 4.1.5 on 2024-03-17 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0003_viewedproducts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviews",
            new_name="Review",
        ),
        migrations.RenameModel(
            old_name="ViewedProducts",
            new_name="ViewedProduct",
        ),
    ]
