# Generated by Django 5.0.3 on 2024-05-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0010_alter_order_options_alter_orderitem_options_and_more"),
        ("pay", "0012_merge_20240520_1605"),
    ]

    operations = []
