# Generated by Django 5.0.3 on 2024-05-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0016_order_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment",
            new_name="payment_type",
        ),
    ]
